---
title: "Effects of Work Shift and Total Excersize Time on Weight Gain"
author: "Paul Hunt, Brandon Kill, Brendan Winters"
date: "9/25/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(ggplot2)
library(dagitty)
library(lavaan)
library(lme4)
library(pscl)
library(faraway)
library(alr4)
library(censReg)
library(ggpubr)
library(tidyverse)

cb_palette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

data <- read_xlsx("Practicum 1 Data.xlsx")
p1.Data <- data[c("Job", "dept", "shift", "gender", "Age", "height", "weightgain", "lbs_gained", "bweight", "BMI", "Vig ex Time", "Walk ex Time", "Mod ex time", "Total_Met_Min")]
names(p1.Data)[names(p1.Data)=="Vig ex Time"] <- "Vig_ex_Time"
names(p1.Data)[names(p1.Data)=="Walk ex Time"] <- "Walk_ex_Time"
names(p1.Data)[names(p1.Data)=="Mod ex time"] <- "Mod_ex_Time"

p1.Data$Job  <- as.factor(p1.Data$Job)
p1.Data$shift  <- factor(p1.Data$shift, levels = c("7am", "8am", "9am", "10am","11am","12pm","1pm","2pm", "other"))
p1.Data$oshift <- unclass(p1.Data$shift)
p1.Data$gender  <- as.factor(p1.Data$gender)
p1.Data$dept  <- as.factor(p1.Data$dept)
p1.Data$weightgain  <- as.factor(p1.Data$weightgain)

p1.Data$Total_Met_Min <- 8*p1.Data$Vig_ex_Time + 4*p1.Data$Mod_ex_Time + 3.3*p1.Data$Walk_ex_Time
p1.Data$lbs_gained[p1.Data$weightgain == "No"] <- 0
p1.Data <- p1.Data[is.na(p1.Data$lbs_gained) == FALSE,]
p1.Data$beg_weight <- p1.Data$bweight-p1.Data$lbs_gained 
```

## Causal Inference
```{r}
CI.graph <- dagitty('dag {
Job             [pos="0,1"]
Dept.           [pos="1,1"]
Walk_ET         [pos="3,1"]
Mod.ET          [pos="4,1"]
Vig.ET          [pos="5,1"]
Shift           [pos="2,2"]
Total_Met.Min   [pos="4,2"]
Age             [pos="5,3"]
Gender          [pos="6,3"] 
Weight_Gain     [pos="3,4"]

Job -> Dept. -> Shift
Job -> Shift -> Total_Met.Min
Shift -> Weight_Gain 
Walk_ET -> Total_Met.Min
Mod.ET -> Total_Met.Min
Vig.ET -> Total_Met.Min -> Weight_Gain
Age -> Total_Met.Min
Age -> Weight_Gain
Gender -> Total_Met.Min
Gender -> Weight_Gain
}')

plot(CI.graph)
```

## Plotting the Predictors on Weight Gain
```{r}
ggplot(p1.Data, aes(x=Total_Met_Min, y=lbs_gained, color=gender)) +geom_point()
```

```{r}
gg1 <- ggplot(na.omit(p1.Data), aes(x=Age, y=lbs_gained, color=gender)) + geom_point()
gg2 <- ggplot(na.omit(p1.Data), aes(x=Age, y=lbs_gained, color=gender)) + geom_boxplot()

```

```{r}
library(tidyverse)

# color blind pallet - we were told to use it in EDA
cb_palette = c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

ggplot(na.omit(p1.Data), aes(x=shift, y=lbs_gained, color=gender)) + geom_boxplot() +
  scale_color_manual(values  =  cb_palette)

p1.Data1 <- na.omit(p1.Data)

  
is_outlier <- function(x) {
  return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))
}

p1.Data1 %>%
  group_by(shift) %>%
  mutate(outlier = ifelse(is_outlier(lbs_gained), lbs_gained, as.numeric(NA))) %>%
  ggplot(., aes(x = shift, y = lbs_gained, color = gender)) +
    geom_boxplot() +
    geom_text(aes(label = outlier), na.rm = TRUE, hjust = -0.3) +
  scale_color_manual(values  =  cb_palette)

p1.Data.out <- p1.Data1 %>%
                  group_by(shift) %>%
                  mutate(outlier = ifelse(is_outlier(lbs_gained), "Yes", "No"))
p1.Data2 <- p1.Data.out %>%
                filter(outlier == "No")
```

```{r}
ggplot(p1.Data2, aes(x=beg_weight, y=lbs_gained, color=gender)) +geom_point()
```

## ZIP Model
```{r Model Estimation}
zipmod <- zeroinfl(round(lbs_gained,0)~oshift+I(Total_Met_Min/100)+beg_weight*gender+Age*gender, data = p1.Data1)
zipmod2 <- zeroinfl(round(lbs_gained,0)~oshift+I(Total_Met_Min/100)+beg_weight*gender+Age*gender, data = p1.Data2)
zipmod3 <- zeroinfl(round(lbs_gained,0)~oshift+I(Total_Met_Min/100)+beg_weight*gender+Age*gender, data = p1.Data3)
summary(zipmod)
summary(zipmod2)
summary(zipmod3)
```

```{r Diagnostic Plots}
plot(log(fitted(zipmod2)), log((p1.Data2$lbs_gained-fitted(zipmod2))^2),
     xlab=expression(hat(mu)[i]),
     ylab=expression((y[i]-hat(mu)[i])^2),
     main = "Estimated Variance vs. Estimated Mean")
abline(0,1)
halfnorm(residuals(zipmod2))
plot( fitted(zipmod2), resid(zipmod2))
abline(0,0)
```

# Results



















